postgresTestApp:
  nameOverride: postgres-test-app
  image:
    name: ghcr.io/gattma/postgres-test-app
    tag: 1.0.0
  route:
    enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
