name: Release Containerimage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: source-version
        id: source-version
        run: |
          echo "::set-output name=version::$(cat version)"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: db-test-app
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: src/main/docker/Dockerfile.jvm
          directory:  .
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }},latest